# Pull the base image
FROM node:22-alpine

# Set the working directory
WORKDIR /usr/app

# Copy app dependencies to container
RUN npm install -g pnpm
COPY  package.json pnpm-lock.yaml* ./

# Install dependencies
RUN pnpm install

# Copy code from host to container
COPY . .

# Expose Port
EXPOSE 5173

# Deploy app for local development
CMD ["pnpm","run","dev"]